### ISSUE TITLE
NFS on CCEE

### ISSUE THREAD

**Issue by tmilos77** [kyma-project/cloud-manager#364]
**Description**

- [x] Manila CSI driver research #474 
- [x] Reconciler implementation
  - [x] KCP Scope #361 #365 
  - [x] KCP Implementation in NfsInstance #499 
  - [x] SKR SapNfsVolume #1009 
  - [x] IpRange #1448 
- [x] CCEE credentials and permissions backlog#6704
- [x] Busola UI
- [x] E2E demo cloud-manager-infra#44
- [x] Documentation
- [x] Rollout
  - [x] Dev
  - [x] Stage
  - [ ] Prod
- [ ] Pricing [Internal issue](https://github.tools.sap/kyma/consumption-reporter/issues/430)
- [ ] GA

**Comment by tmilos77** [comment]
The Kyma KCP egress IP addresses are supposedly added to CCEE ACL allow list. The only thing we're left with is to fake API domain names, waiting for SRE call on how to proceed with it.
