### ISSUE TITLE
Redis - GCP

### ISSUE THREAD

**Issue by ngrkajac** [kyma-project/cloud-manager#398]
**GCP Redis is Ready for Staging**

- General
  - [x] Redis instance can be provisioned and deprovisioned.
  - [x] Auth secret containing endpoints and auth string is provided and managed by the cloud-manager. It shares the instance lifecycle.
  - [x] Gcp Docs
  - [x] Gcp Busola
  - [x] SKR Updating state
  - [x] prevent IpRange delete if instance exists (https://github.com/kyma-project/cloud-manager/issues/543)
  - Scenario test for Update (wont do)
  - [x] E2E test
 
- Redis can be instantiated with definable:
  - [x] `tier`
  - [x] `memorySizeGb`
  - [x] `redisVersion`
  - [x] `redisConfigs`
  - [x] `auth` (enabled/disabled)
  - [x] `inTransitEncryption` **(todo: CA Certificate needs to be provided to client)**
  - [x] `ipRange`
    - [x] custom value (explicit)
    - [x] default (implicit)  
  - [x] `maintenancePolicy` (https://github.com/kyma-project/cloud-manager/issues/426)
  - [x] provide CA Certificate in auth secret when encryption is set to tls (https://github.com/kyma-project/cloud-manager/issues/427)
  - [x] mutable `memorySizeGb` (https://github.com/kyma-project/cloud-manager/issues/428)
  - [x] mutable `redisConfigs` (https://github.com/kyma-project/cloud-manager/issues/429)
  - [x] mutable `auth` https://github.com/kyma-project/cloud-manager/issues/430
  - [x] mutable `maintenancePolicy` (https://github.com/kyma-project/cloud-manager/issues/507)
  - [x] label resource at cloud provider (https://github.com/kyma-project/cloud-manager/issues/432)
