### ISSUE TITLE
Redis - AWS

### ISSUE THREAD

**Issue by ngrkajac** [kyma-project/cloud-manager#486]
- General
  - [x] Redis instance can be provisioned and deprovisioned.
  - [x] Auth secret containing endpoints and auth string is provided and managed by the cloud-manager. It shares the instance lifecycle.
  - [x] Aws Docs
  - [x] Aws Busola
  - [x] SKR Updating state
  - [x] prevent IpRange delete if instance exists (https://github.com/kyma-project/cloud-manager/issues/543)
  -  Scenario test for Update (wont do)
  - [x] E2E test

- Redis can be instantiated with definable:
  - [x] `cacheNodeType`
  - [x] `engineVersion` (Redis version)
  - [x] `parameters` (Redis Configurations) (mutable)
  - [x] `autoMinorVersionUpgrade`
  - [x] `ipRange`
    - [x] custom value (explicit)
    - [x] default (implicit)
  - [x] `auth` (https://github.com/kyma-project/cloud-manager/issues/434)
  - [x] `inTransitEncryption` (https://github.com/kyma-project/cloud-manager/issues/435)
  - [x] `maintanencePolicy` (https://github.com/kyma-project/cloud-manager/issues/436)
  - [x] mutable `parameters`
  - [x] mutable `cacheNodeType` (https://github.com/kyma-project/cloud-manager/issues/437)
  - mutable `engineVersion` (wont do)
  - [x] mutable `maintanencePolicy` (https://github.com/kyma-project/cloud-manager/issues/579)
  - [x] mutable `autoMinorVersionUpgrade` (https://github.com/kyma-project/cloud-manager/issues/439)
  - [x] mutable `transitEncryptionEnabled` (https://github.com/kyma-project/cloud-manager/issues/572)
  - [x] mutable `authEnabled` (https://github.com/kyma-project/cloud-manager/issues/580)
