### ISSUE TITLE
Redis - Azure

### ISSUE THREAD

**Issue by ngrkajac** [kyma-project/cloud-manager#487]
- General:
  - [x] Redis instance can be provisioned and deprovisioned.
  - [x] Auth secret containing endpoints and auth string is provided and managed by the cloud-manager. It shares the instance lifecycle.
  - [x] Azure Docs
  - [x] Azure Busola
  - [x] SKR Updating state
  - [x] E2E test

- Redis can be instantiated with definable:
  - [x] `SKU.Capacity` (Family is hardcoded to Premium)
  - <del> [ ] `EnableNonSslPort` </del> - SSL is enabled by default and can not be disabled
  - [x] `RedisVersion`
  - [x] `ShardCount`
  - [x] `ReplicasPerPrimary`
  - [x] `RedisConfiguration`
  - [x] #451
  - [x] #452
  - [x] #447 
  - [x] #480
