### ISSUE TITLE
[FeatureFlags] Sunset `ipRangeAutomaticCidrAllocation`

### ISSUE THREAD

**Issue by dushanpantic** [kyma-project/cloud-manager#587]
**Description**

As this flag is enabled on all of our landscapes, and no issues were detected, we should remove it and make its behavior baseline.

**Reasons**

**Attachments**

**Tasks**
* [x] Stop using FF in cloud-managed #616
* [x] Remove FF from cloud-manager #864
* [x] Delete FF from the config [config#5935](https://github.tools.sap/kyma/management-plane-config/pull/5935)
  * [x] **MUST NOT BE DONE BEFORE #616 IS DEPLOYED TO PROD**
